# Imports

In [152]:
# data processing
import numpy as np
import pandas as pd 

# machine learning
from keras.models import Sequential
from keras.layers import Dense
from scikeras.wrappers import KerasClassifier, KerasRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

# utils
import time
from datetime import timedelta

In [153]:
# Input files
file_train='../data/train.csv'
file_test='../data/test.csv'

In [154]:
seed = 69
np.random.seed(seed)

In [155]:
train_df = pd.read_csv(file_train,index_col='PassengerId')

In [156]:
# Show the columns
train_df.columns.values

array(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'], dtype=object)

In [157]:
# Show the shape
train_df.shape

(891, 11)

In [158]:
# preview the training dara
train_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [159]:
# Show that there is NaN data (Age,Fare Embarked), that needs to be handled during data cleansing
train_df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [160]:
train_df.Fare.sort_values()

PassengerId
816      0.0000
807      0.0000
414      0.0000
482      0.0000
303      0.0000
         ...
439    263.0000
342    263.0000
738    512.3292
680    512.3292
259    512.3292
Name: Fare, Length: 891, dtype: float64

A function for simple data cleansing <br>
- Drop unwanted features ['Name', 'Ticket', 'Cabin']<br>
- Fill missing data: Age and Fare with the mean, Embarked with most frequent value<br>
- Convert categorical features into numeric<br>
- Convert Embarked to one-hot<br>

In [161]:
def prep_data(df):
    # Drop unwanted features
    df = df.drop(['Name', 'Ticket', 'Cabin'], axis=1)
    
    # Fill missing data: Age and Fare with the mean, Embarked with most frequent value
    df[['Age']] = df[['Age']].fillna(value=df[['Age']].mean())
    df[['Fare']] = df[['Fare']].fillna(value=df[['Fare']].mean())
    df[['Embarked']] = df[['Embarked']].fillna(value=df['Embarked'].value_counts().idxmax())
    
    # Convert categorical  features into numeric
    df['Sex'] = df['Sex'].map( {'female': 1, 'male': 0} ).astype(int)
      
    # Convert Embarked to one-hot
    enbarked_one_hot = pd.get_dummies(df['Embarked'], prefix='Embarked')
    df = df.drop('Embarked', axis=1)
    df = df.join(enbarked_one_hot)

    return df

In [162]:
train_df = prep_data(train_df)
train_df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [163]:
# X contains all columns except 'Survived'  
X = train_df.drop(['Survived'], axis=1).values.astype(float)

# It is almost always a good idea to perform some scaling of input values when using neural network models (jb).

scale = StandardScaler()
X = scale.fit_transform(X)

# Y is just the 'Survived' column
Y = train_df['Survived'].values

Simple Network using Keras <br>
- Input layer with 16 neuron (units/outputs).<br>
- Two hidden layers.<br>
- Output layer with a single neuron and sigmoid activation function to output a value between 0 and 1.<br>
- Optimizer and init will be searched with GridSearch.<br>

In [164]:
verbose=2 # Use in classifier

In [165]:
def create_model(optimizer='adam', init='uniform') -> Sequential:
    # create model
    if verbose: print("**Create model with optimizer: %s; init: %s" % (optimizer, init) )
    model = Sequential()
    model.add(Dense(16, input_dim=X.shape[1], kernel_initializer=init, activation='relu'))
    model.add(Dense(8, kernel_initializer=init, activation='relu'))
    model.add(Dense(4, kernel_initializer=init, activation='relu'))
    model.add(Dense(1, kernel_initializer=init, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

In [166]:
run_gridsearch = False

if run_gridsearch:
    
    start_time = time.time()
    if verbose: print (time.strftime( "%H:%M:%S " + "GridSearch started ... " ) )
    optimizers = ['rmsprop', 'adam']
    inits = ['glorot_uniform', 'normal', 'uniform']
    epochs = [50, 100, 200, 400]
    batches = [5, 10, 20]
    
    model = KerasClassifier(build_fn=create_model, verbose=verbose)
    
    param_grid = dict(optimizer=optimizers, epochs=epochs, batch_size=batches, init=inits)
    grid = GridSearchCV(estimator=model, param_grid=param_grid)
    grid_result = grid.fit(X, Y)
    
    # summarize results
    print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
    means = grid_result.cv_results_['mean_test_score']
    stds = grid_result.cv_results_['std_test_score']
    params = grid_result.cv_results_['params']
    if verbose: 
        for mean, stdev, param in zip(means, stds, params):
            print("%f (%f) with: %r" % (mean, stdev, param))
        elapsed_time = time.time() - start_time  
        print ("Time elapsed: ",timedelta(seconds=elapsed_time))
        
    best_epochs = grid_result.best_params_['epochs']
    best_batch_size = grid_result.best_params_['batch_size']
    best_init = grid_result.best_params_['init']
    best_optimizer = grid_result.best_params_['optimizer']
    
else:
    # pre-selected paramters
    best_epochs = 200
    best_batch_size = 5
    best_init = 'glorot_uniform'
    best_optimizer = 'rmsprop'

In [167]:
# Create a classifier with best parameters
model_pred = KerasClassifier(build_fn=create_model, optimizer=best_optimizer, init=best_init, epochs=best_epochs, batch_size=best_batch_size, verbose=verbose)
model_pred.fit(X, Y)

# Read test data
test_df = pd.read_csv(file_test,index_col='PassengerId')
# Prep and clean data
test_df = prep_data(test_df)
# Create X_test
X_test = test_df.values.astype(float)
# Scaling
X_test = scale.transform(X_test)

# Predict 'Survived'
prediction = model_pred.predict(X_test)

**Create model with optimizer: adam; init: glorot_uniform
Epoch 1/200

c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

179/179 - 1s - 5ms/step - accuracy: 0.6184 - loss: 0.6165
Epoch 2/200
179/179 - 0s - 911us/step - accuracy: 0.7374 - loss: 0.5383
Epoch 3/200
179/179 - 0s - 981us/step - accuracy: 0.8227 - loss: 0.5081
Epoch 4/200
179/179 - 0s - 969us/step - accuracy: 0.8193 - loss: 0.4834
Epoch 5/200
179/179 - 0s - 979us/step - accuracy: 0.8193 - loss: 0.4603
Epoch 6/200
179/179 - 0s - 928us/step - accuracy: 0.8193 - loss: 0.4329
Epoch 7/200
179/179 - 0s - 976us/step - accuracy: 0.8272 - loss: 0.4182
Epoch 8/200
179/179 - 0s - 923us/step - accuracy: 0.8328 - loss: 0.4080
Epoch 9/200
179/179 - 0s - 938us/step - accuracy: 0.8316 - loss: 0.4041
Epoch 10/200
179/179 - 0s - 907us/step - accuracy: 0.8316 - loss: 0.4001
Epoch 11/200
179/179 - 0s - 914us/step - accuracy: 0.8339 - loss: 0.3957
Epoch 12/200
179/179 - 0s - 912us/step - accuracy: 0.8361 - loss: 0.3945
Epoch 13/200
179/179 - 0s - 952us/step - accuracy: 0.8406 - loss: 0.3912
Epoch 14/200
179/179 - 0s - 995us/step - accuracy: 0.8406 - loss: 0.3872
Epoch 15/200
179/179 - 0s - 978us/step - accuracy: 0.8418 - loss: 0.3860
Epoch 16/200
179/179 - 0s - 1ms/step - accuracy: 0.8418 - loss: 0.3861
Epoch 17/200
179/179 - 0s - 953us/step - accuracy: 0.8373 - loss: 0.3828
Epoch 18/200
179/179 - 0s - 930us/step - accuracy: 0.8440 - loss: 0.3785
Epoch 19/200
179/179 - 0s - 925us/step - accuracy: 0.8440 - loss: 0.3782
Epoch 20/200
179/179 - 0s - 893us/step - accuracy: 0.8418 - loss: 0.3758
Epoch 21/200
179/179 - 0s - 947us/step - accuracy: 0.8440 - loss: 0.3746
Epoch 22/200
179/179 - 0s - 877us/step - accuracy: 0.8451 - loss: 0.3724
Epoch 23/200
179/179 - 0s - 938us/step - accuracy: 0.8496 - loss: 0.3702
Epoch 24/200
179/179 - 0s - 938us/step - accuracy: 0.8462 - loss: 0.3700
Epoch 25/200
179/179 - 0s - 935us/step - accuracy: 0.8429 - loss: 0.3696
Epoch 26/200
179/179 - 0s - 890us/step - accuracy: 0.8451 - loss: 0.3671
Epoch 27/200
179/179 - 0s - 948us/step - accuracy: 0.8507 - loss: 0.3676
Epoch 28/200
179/179 - 0s - 954us/step - accuracy: 0.8575 - loss: 0.3642
Epoch 29/200
179/179 - 0s - 920us/step - accuracy: 0.8496 - loss: 0.3633
Epoch 30/200
179/179 - 0s - 923us/step - accuracy: 0.8530 - loss: 0.3611
Epoch 31/200
179/179 - 0s - 919us/step - accuracy: 0.8496 - loss: 0.3640
Epoch 32/200
179/179 - 0s - 928us/step - accuracy: 0.8530 - loss: 0.3624
Epoch 33/200
179/179 - 0s - 982us/step - accuracy: 0.8519 - loss: 0.3593
Epoch 34/200
179/179 - 0s - 888us/step - accuracy: 0.8519 - loss: 0.3602
Epoch 35/200
179/179 - 0s - 940us/step - accuracy: 0.8552 - loss: 0.3581
Epoch 36/200
179/179 - 0s - 903us/step - accuracy: 0.8507 - loss: 0.3586
Epoch 37/200
179/179 - 0s - 934us/step - accuracy: 0.8519 - loss: 0.3571
Epoch 38/200
179/179 - 0s - 958us/step - accuracy: 0.8552 - loss: 0.3553
Epoch 39/200
179/179 - 0s - 976us/step - accuracy: 0.8575 - loss: 0.3538
Epoch 40/200
179/179 - 0s - 887us/step - accuracy: 0.8552 - loss: 0.3557
Epoch 41/200
179/179 - 0s - 888us/step - accuracy: 0.8541 - loss: 0.3557
Epoch 42/200
179/179 - 0s - 937us/step - accuracy: 0.8552 - loss: 0.3538
Epoch 43/200
179/179 - 0s - 913us/step - accuracy: 0.8575 - loss: 0.3526
Epoch 44/200
179/179 - 0s - 898us/step - accuracy: 0.8563 - loss: 0.3533
Epoch 45/200
179/179 - 0s - 992us/step - accuracy: 0.8563 - loss: 0.3501
Epoch 46/200
179/179 - 0s - 964us/step - accuracy: 0.8563 - loss: 0.3501
Epoch 47/200
179/179 - 0s - 939us/step - accuracy: 0.8575 - loss: 0.3501
Epoch 48/200
179/179 - 0s - 930us/step - accuracy: 0.8496 - loss: 0.3520
Epoch 49/200
179/179 - 0s - 955us/step - accuracy: 0.8575 - loss: 0.3490
Epoch 50/200
179/179 - 0s - 890us/step - accuracy: 0.8575 - loss: 0.3472
Epoch 51/200
179/179 - 0s - 934us/step - accuracy: 0.8552 - loss: 0.3491
Epoch 52/200
179/179 - 0s - 953us/step - accuracy: 0.8575 - loss: 0.3465
Epoch 53/200
179/179 - 0s - 943us/step - accuracy: 0.8676 - loss: 0.3471
Epoch 54/200
179/179 - 0s - 947us/step - accuracy: 0.8519 - loss: 0.3464
Epoch 55/200
179/179 - 0s - 987us/step - accuracy: 0.8563 - loss: 0.3445
Epoch 56/200
179/179 - 0s - 931us/step - accuracy: 0.8653 - loss: 0.3445
Epoch 57/200
179/179 - 0s - 927us/step - accuracy: 0.8575 - loss: 0.3449
Epoch 58/200
179/179 - 0s - 899us/step - accuracy: 0.8563 - loss: 0.3443
Epoch 59/200
179/179 - 0s - 923us/step - accuracy: 0.8586 - loss: 0.3443
Epoch 60/200
179/179 - 0s - 917us/step - accuracy: 0.8563 - loss: 0.3437
Epoch 61/200
179/179 - 0s - 981us/step - accuracy: 0.8586 - loss: 0.3442
Epoch 62/200
179/179 - 0s - 903us/step - accuracy: 0.8620 - loss: 0.3423
Epoch 63/200
179/179 - 0s - 921us/step - accuracy: 0.8563 - loss: 0.3414
Epoch 64/200
179/179 - 0s - 895us/step - accuracy: 0.8664 - loss: 0.3393
Epoch 65/200
179/179 - 0s - 881us/step - accuracy: 0.8664 - loss: 0.3380
Epoch 66/200
179/179 - 0s - 884us/step - accuracy: 0.8620 - loss: 0.3403
Epoch 67/200
179/179 - 0s - 887us/step - accuracy: 0.8620 - loss: 0.3382
Epoch 68/200
179/179 - 0s - 882us/step - accuracy: 0.8687 - loss: 0.3380
Epoch 69/200
179/179 - 0s - 893us/step - accuracy: 0.8631 - loss: 0.3372
Epoch 70/200
179/179 - 0s - 890us/step - accuracy: 0.8631 - loss: 0.3364
Epoch 71/200
179/179 - 0s - 890us/step - accuracy: 0.8676 - loss: 0.3382
Epoch 72/200
179/179 - 0s - 900us/step - accuracy: 0.8642 - loss: 0.3367
Epoch 73/200
179/179 - 0s - 895us/step - accuracy: 0.8608 - loss: 0.3389
Epoch 74/200
179/179 - 0s - 888us/step - accuracy: 0.8653 - loss: 0.3358
Epoch 75/200
179/179 - 0s - 888us/step - accuracy: 0.8575 - loss: 0.3336
Epoch 76/200
179/179 - 0s - 882us/step - accuracy: 0.8597 - loss: 0.3369
Epoch 77/200
179/179 - 0s - 885us/step - accuracy: 0.8620 - loss: 0.3351
Epoch 78/200
179/179 - 0s - 879us/step - accuracy: 0.8687 - loss: 0.3304
Epoch 79/200
179/179 - 0s - 893us/step - accuracy: 0.8631 - loss: 0.3309
Epoch 80/200
179/179 - 0s - 901us/step - accuracy: 0.8608 - loss: 0.3319
Epoch 81/200
179/179 - 0s - 892us/step - accuracy: 0.8620 - loss: 0.3311
Epoch 82/200
179/179 - 0s - 889us/step - accuracy: 0.8664 - loss: 0.3293
Epoch 83/200
179/179 - 0s - 908us/step - accuracy: 0.8597 - loss: 0.3289
Epoch 84/200
179/179 - 0s - 949us/step - accuracy: 0.8597 - loss: 0.3297
Epoch 85/200
179/179 - 0s - 889us/step - accuracy: 0.8664 - loss: 0.3287
Epoch 86/200
179/179 - 0s - 897us/step - accuracy: 0.8653 - loss: 0.3294
Epoch 87/200
179/179 - 0s - 881us/step - accuracy: 0.8676 - loss: 0.3293
Epoch 88/200
179/179 - 0s - 917us/step - accuracy: 0.8631 - loss: 0.3256
Epoch 89/200
179/179 - 0s - 883us/step - accuracy: 0.8664 - loss: 0.3284
Epoch 90/200
179/179 - 0s - 885us/step - accuracy: 0.8642 - loss: 0.3276
Epoch 91/200
179/179 - 0s - 900us/step - accuracy: 0.8631 - loss: 0.3273
Epoch 92/200
179/179 - 0s - 924us/step - accuracy: 0.8631 - loss: 0.3269
Epoch 93/200
179/179 - 0s - 970us/step - accuracy: 0.8608 - loss: 0.3278
Epoch 94/200
179/179 - 0s - 903us/step - accuracy: 0.8687 - loss: 0.3260
Epoch 95/200
179/179 - 0s - 944us/step - accuracy: 0.8676 - loss: 0.3278
Epoch 96/200
179/179 - 0s - 981us/step - accuracy: 0.8698 - loss: 0.3269
Epoch 97/200
179/179 - 0s - 929us/step - accuracy: 0.8642 - loss: 0.3244
Epoch 98/200
179/179 - 0s - 886us/step - accuracy: 0.8653 - loss: 0.3231
Epoch 99/200
179/179 - 0s - 923us/step - accuracy: 0.8664 - loss: 0.3227
Epoch 100/200
179/179 - 0s - 899us/step - accuracy: 0.8664 - loss: 0.3247
Epoch 101/200
179/179 - 0s - 947us/step - accuracy: 0.8676 - loss: 0.3218
Epoch 102/200
179/179 - 0s - 900us/step - accuracy: 0.8687 - loss: 0.3221
Epoch 103/200
179/179 - 0s - 902us/step - accuracy: 0.8676 - loss: 0.3210
Epoch 104/200
179/179 - 0s - 904us/step - accuracy: 0.8698 - loss: 0.3225
Epoch 105/200
179/179 - 0s - 899us/step - accuracy: 0.8597 - loss: 0.3246
Epoch 106/200
179/179 - 0s - 896us/step - accuracy: 0.8664 - loss: 0.3212
Epoch 107/200
179/179 - 0s - 896us/step - accuracy: 0.8676 - loss: 0.3222
Epoch 108/200
179/179 - 0s - 920us/step - accuracy: 0.8664 - loss: 0.3250
Epoch 109/200
179/179 - 0s - 894us/step - accuracy: 0.8721 - loss: 0.3239
Epoch 110/200
179/179 - 0s - 898us/step - accuracy: 0.8608 - loss: 0.3211
Epoch 111/200
179/179 - 0s - 922us/step - accuracy: 0.8620 - loss: 0.3204
Epoch 112/200
179/179 - 0s - 895us/step - accuracy: 0.8721 - loss: 0.3190
Epoch 113/200
179/179 - 0s - 907us/step - accuracy: 0.8687 - loss: 0.3193
Epoch 114/200
179/179 - 0s - 885us/step - accuracy: 0.8709 - loss: 0.3197
Epoch 115/200
179/179 - 0s - 943us/step - accuracy: 0.8709 - loss: 0.3165
Epoch 116/200
179/179 - 0s - 912us/step - accuracy: 0.8664 - loss: 0.3197
Epoch 117/200
179/179 - 0s - 958us/step - accuracy: 0.8732 - loss: 0.3174
Epoch 118/200
179/179 - 0s - 882us/step - accuracy: 0.8608 - loss: 0.3229
Epoch 119/200
179/179 - 0s - 873us/step - accuracy: 0.8664 - loss: 0.3174
Epoch 120/200
179/179 - 0s - 876us/step - accuracy: 0.8732 - loss: 0.3179
Epoch 121/200
179/179 - 0s - 882us/step - accuracy: 0.8709 - loss: 0.3164
Epoch 122/200
179/179 - 0s - 876us/step - accuracy: 0.8721 - loss: 0.3169
Epoch 123/200
179/179 - 0s - 941us/step - accuracy: 0.8676 - loss: 0.3163
Epoch 124/200
179/179 - 0s - 897us/step - accuracy: 0.8687 - loss: 0.3177
Epoch 125/200
179/179 - 0s - 922us/step - accuracy: 0.8676 - loss: 0.3163
Epoch 126/200
179/179 - 0s - 897us/step - accuracy: 0.8687 - loss: 0.3185
Epoch 127/200
179/179 - 0s - 925us/step - accuracy: 0.8687 - loss: 0.3178
Epoch 128/200
179/179 - 0s - 889us/step - accuracy: 0.8631 - loss: 0.3173
Epoch 129/200
179/179 - 0s - 918us/step - accuracy: 0.8687 - loss: 0.3156
Epoch 130/200
179/179 - 0s - 878us/step - accuracy: 0.8698 - loss: 0.3173
Epoch 131/200
179/179 - 0s - 908us/step - accuracy: 0.8687 - loss: 0.3145
Epoch 132/200
179/179 - 0s - 898us/step - accuracy: 0.8698 - loss: 0.3156
Epoch 133/200
179/179 - 0s - 965us/step - accuracy: 0.8676 - loss: 0.3160
Epoch 134/200
179/179 - 0s - 871us/step - accuracy: 0.8709 - loss: 0.3124
Epoch 135/200
179/179 - 0s - 934us/step - accuracy: 0.8709 - loss: 0.3120
Epoch 136/200
179/179 - 0s - 935us/step - accuracy: 0.8698 - loss: 0.3150
Epoch 137/200
179/179 - 0s - 898us/step - accuracy: 0.8732 - loss: 0.3165
Epoch 138/200
179/179 - 0s - 883us/step - accuracy: 0.8676 - loss: 0.3144
Epoch 139/200
179/179 - 0s - 890us/step - accuracy: 0.8698 - loss: 0.3122
Epoch 140/200
179/179 - 0s - 887us/step - accuracy: 0.8709 - loss: 0.3157
Epoch 141/200
179/179 - 0s - 876us/step - accuracy: 0.8687 - loss: 0.3147
Epoch 142/200
179/179 - 0s - 888us/step - accuracy: 0.8721 - loss: 0.3144
Epoch 143/200
179/179 - 0s - 892us/step - accuracy: 0.8698 - loss: 0.3140
Epoch 144/200
179/179 - 0s - 877us/step - accuracy: 0.8586 - loss: 0.3140
Epoch 145/200
179/179 - 0s - 880us/step - accuracy: 0.8642 - loss: 0.3136
Epoch 146/200
179/179 - 0s - 860us/step - accuracy: 0.8743 - loss: 0.3115
Epoch 147/200
179/179 - 0s - 885us/step - accuracy: 0.8687 - loss: 0.3134
Epoch 148/200
179/179 - 0s - 898us/step - accuracy: 0.8676 - loss: 0.3144
Epoch 149/200
179/179 - 0s - 903us/step - accuracy: 0.8676 - loss: 0.3113
Epoch 150/200
179/179 - 0s - 901us/step - accuracy: 0.8664 - loss: 0.3113
Epoch 151/200
179/179 - 0s - 900us/step - accuracy: 0.8687 - loss: 0.3131
Epoch 152/200
179/179 - 0s - 896us/step - accuracy: 0.8721 - loss: 0.3101
Epoch 153/200
179/179 - 0s - 943us/step - accuracy: 0.8743 - loss: 0.3125
Epoch 154/200
179/179 - 0s - 882us/step - accuracy: 0.8732 - loss: 0.3117
Epoch 155/200
179/179 - 0s - 945us/step - accuracy: 0.8676 - loss: 0.3104
Epoch 156/200
179/179 - 0s - 898us/step - accuracy: 0.8777 - loss: 0.3097
Epoch 157/200
179/179 - 0s - 887us/step - accuracy: 0.8765 - loss: 0.3104
Epoch 158/200
179/179 - 0s - 890us/step - accuracy: 0.8721 - loss: 0.3085
Epoch 159/200
179/179 - 0s - 967us/step - accuracy: 0.8664 - loss: 0.3078
Epoch 160/200
179/179 - 0s - 903us/step - accuracy: 0.8732 - loss: 0.3126
Epoch 161/200
179/179 - 0s - 974us/step - accuracy: 0.8721 - loss: 0.3110
Epoch 162/200
179/179 - 0s - 912us/step - accuracy: 0.8743 - loss: 0.3096
Epoch 163/200
179/179 - 0s - 959us/step - accuracy: 0.8709 - loss: 0.3094
Epoch 164/200
179/179 - 0s - 901us/step - accuracy: 0.8777 - loss: 0.3065
Epoch 165/200
179/179 - 0s - 979us/step - accuracy: 0.8709 - loss: 0.3084
Epoch 166/200
179/179 - 0s - 900us/step - accuracy: 0.8664 - loss: 0.3106
Epoch 167/200
179/179 - 0s - 961us/step - accuracy: 0.8687 - loss: 0.3078
Epoch 168/200
179/179 - 0s - 913us/step - accuracy: 0.8754 - loss: 0.3078
Epoch 169/200
179/179 - 0s - 928us/step - accuracy: 0.8799 - loss: 0.3044
Epoch 170/200
179/179 - 0s - 938us/step - accuracy: 0.8721 - loss: 0.3076
Epoch 171/200
179/179 - 0s - 965us/step - accuracy: 0.8709 - loss: 0.3086
Epoch 172/200
179/179 - 0s - 930us/step - accuracy: 0.8810 - loss: 0.3099
Epoch 173/200
179/179 - 0s - 919us/step - accuracy: 0.8653 - loss: 0.3105
Epoch 174/200
179/179 - 0s - 902us/step - accuracy: 0.8698 - loss: 0.3080
Epoch 175/200
179/179 - 0s - 944us/step - accuracy: 0.8732 - loss: 0.3121
Epoch 176/200
179/179 - 0s - 909us/step - accuracy: 0.8642 - loss: 0.3058
Epoch 177/200
179/179 - 0s - 929us/step - accuracy: 0.8698 - loss: 0.3063
Epoch 178/200
179/179 - 0s - 877us/step - accuracy: 0.8698 - loss: 0.3059
Epoch 179/200
179/179 - 0s - 929us/step - accuracy: 0.8709 - loss: 0.3058
Epoch 180/200
179/179 - 0s - 918us/step - accuracy: 0.8732 - loss: 0.3099
Epoch 181/200
179/179 - 0s - 943us/step - accuracy: 0.8721 - loss: 0.3095
Epoch 182/200
179/179 - 0s - 889us/step - accuracy: 0.8732 - loss: 0.3068
Epoch 183/200
179/179 - 0s - 968us/step - accuracy: 0.8664 - loss: 0.3063
Epoch 184/200
179/179 - 0s - 892us/step - accuracy: 0.8698 - loss: 0.3079
Epoch 185/200
179/179 - 0s - 981us/step - accuracy: 0.8777 - loss: 0.3064
Epoch 186/200
179/179 - 0s - 899us/step - accuracy: 0.8698 - loss: 0.3092
Epoch 187/200
179/179 - 0s - 946us/step - accuracy: 0.8765 - loss: 0.3031
Epoch 188/200
179/179 - 0s - 918us/step - accuracy: 0.8698 - loss: 0.3060
Epoch 189/200
179/179 - 0s - 937us/step - accuracy: 0.8709 - loss: 0.3039
Epoch 190/200
179/179 - 0s - 885us/step - accuracy: 0.8810 - loss: 0.3031
Epoch 191/200
179/179 - 0s - 873us/step - accuracy: 0.8698 - loss: 0.3042
Epoch 192/200
179/179 - 0s - 901us/step - accuracy: 0.8754 - loss: 0.3038
Epoch 193/200
179/179 - 0s - 947us/step - accuracy: 0.8788 - loss: 0.3062
Epoch 194/200
179/179 - 0s - 913us/step - accuracy: 0.8698 - loss: 0.3074
Epoch 195/200
179/179 - 0s - 945us/step - accuracy: 0.8743 - loss: 0.3037
Epoch 196/200
179/179 - 0s - 915us/step - accuracy: 0.8754 - loss: 0.3038
Epoch 197/200
179/179 - 0s - 921us/step - accuracy: 0.8698 - loss: 0.3034
Epoch 198/200
179/179 - 0s - 927us/step - accuracy: 0.8732 - loss: 0.3041
Epoch 199/200
179/179 - 0s - 909us/step - accuracy: 0.8743 - loss: 0.3038
Epoch 200/200
179/179 - 0s - 884us/step - accuracy: 0.8732 - loss: 0.3036
84/84 - 0s - 1ms/step

In [168]:
submission = pd.DataFrame({
    'PassengerId': test_df.index,
    'Survived': prediction
})

submission.sort_values('PassengerId', inplace=True)    
submission.to_csv('submission-simple-cleansing.csv', index=False)

In [169]:
print(prediction.shape)

(418,)

# Part 2 - Predict the missing data in the Age feature

In [170]:
# Read the data
file_train='../data/train.csv'
file_test='../data/test.csv'
    
df_train = pd.read_csv(file_train,index_col='PassengerId')
df_test = pd.read_csv(file_test,index_col='PassengerId')  
l = len(df_train.index)
    

## All data train and test in one dataframe 
dfa = pd.concat([df_train, df_test])

# Drop unwanted features
dfa = dfa.drop(['Name', 'Ticket', 'Cabin'], axis=1)
    
# Fill missing data: Fare with mean, Embarked with most frequent value
dfa[['Fare']] = dfa[['Fare']].fillna(value=dfa[['Fare']].mean())
dfa[['Embarked']] = dfa[['Embarked']].fillna(value=dfa['Embarked'].value_counts().idxmax())
    
# Convert categorical features into numeric
dfa['Sex'] = dfa['Sex'].map( {'female': 1, 'male': 0} ).astype(int)

# Convert 'Embarked' to one-hot
enbarked_one_hot = pd.get_dummies(dfa['Embarked'], prefix='Embarked')
dfa = dfa.drop('Embarked', axis=1)
dfa = dfa.join(enbarked_one_hot)

In [171]:
dfa.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
PassengerId,,,,,,,,,,
1,0.0,3,0,22.0,1,0,7.2500,False,False,True
2,1.0,1,1,38.0,1,0,71.2833,True,False,False
3,1.0,3,1,26.0,0,0,7.9250,False,False,True
4,1.0,1,1,35.0,1,0,53.1000,False,False,True
5,0.0,3,0,35.0,0,0,8.0500,False,False,True

In [172]:
# Split data in to training set (Age not null) and 'to-be-predicted' set (Age in nan)
df_age_train = dfa[dfa.Age.notnull()]
df_age_nan = dfa[dfa.Age.isnull()]

Predict age <br>
- Create input X, output Y and X_test<br>
- The model for the regression. The regression problem may have a single output neuron and the neuron may have no activation function (jb).<br>
- Create a pipeline, do cross-validation and predict<br>
- Generate new input files for the training and test data but with predicted age<br>

In [173]:
# split data into input X and output Y
X = df_age_train.drop(['Age', 'Survived'], axis=1).values.astype(float)
Y = df_age_train['Age'].values.astype(float)

X_test = df_age_nan.drop(['Age', 'Survived'], axis=1).values.astype(float)

def age_model():
    # create model
    model = Sequential()
    model.add(Dense(32, input_dim=X.shape[1], kernel_initializer='normal', activation='relu'))
    model.add(Dense(16, kernel_initializer='normal', activation='relu'))
    model.add(Dense(8, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal'))
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [174]:
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=age_model, epochs=100, batch_size=5, verbose=verbose)))
pipeline = Pipeline(estimators)

In [175]:
kfold = KFold(n_splits=2)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Result: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Epoch 1/100

c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

105/105 - 1s - 6ms/step - loss: 1085.1030
Epoch 2/100
105/105 - 0s - 926us/step - loss: 784.6974
Epoch 3/100
105/105 - 0s - 931us/step - loss: 187.0743
Epoch 4/100
105/105 - 0s - 917us/step - loss: 159.6093
Epoch 5/100
105/105 - 0s - 1ms/step - loss: 156.0351
Epoch 6/100
105/105 - 0s - 916us/step - loss: 153.1585
Epoch 7/100
105/105 - 0s - 925us/step - loss: 151.3333
Epoch 8/100
105/105 - 0s - 926us/step - loss: 150.2538
Epoch 9/100
105/105 - 0s - 942us/step - loss: 149.2234
Epoch 10/100
105/105 - 0s - 920us/step - loss: 148.6994
Epoch 11/100
105/105 - 0s - 959us/step - loss: 148.8624
Epoch 12/100
105/105 - 0s - 916us/step - loss: 147.0875
Epoch 13/100
105/105 - 0s - 943us/step - loss: 147.0017
Epoch 14/100
105/105 - 0s - 923us/step - loss: 146.8462
Epoch 15/100
105/105 - 0s - 930us/step - loss: 145.5003
Epoch 16/100
105/105 - 0s - 911us/step - loss: 144.9095
Epoch 17/100
105/105 - 0s - 935us/step - loss: 144.7384
Epoch 18/100
105/105 - 0s - 922us/step - loss: 143.9784
Epoch 19/100
105/105 - 0s - 953us/step - loss: 144.6987
Epoch 20/100
105/105 - 0s - 938us/step - loss: 143.6097
Epoch 21/100
105/105 - 0s - 957us/step - loss: 142.9703
Epoch 22/100
105/105 - 0s - 955us/step - loss: 142.8999
Epoch 23/100
105/105 - 0s - 936us/step - loss: 142.5521
Epoch 24/100
105/105 - 0s - 931us/step - loss: 142.4877
Epoch 25/100
105/105 - 0s - 929us/step - loss: 141.4916
Epoch 26/100
105/105 - 0s - 936us/step - loss: 141.3342
Epoch 27/100
105/105 - 0s - 937us/step - loss: 141.1198
Epoch 28/100
105/105 - 0s - 928us/step - loss: 141.4141
Epoch 29/100
105/105 - 0s - 939us/step - loss: 142.5547
Epoch 30/100
105/105 - 0s - 915us/step - loss: 140.0656
Epoch 31/100
105/105 - 0s - 952us/step - loss: 141.0654
Epoch 32/100
105/105 - 0s - 942us/step - loss: 140.2872
Epoch 33/100
105/105 - 0s - 941us/step - loss: 139.8675
Epoch 34/100
105/105 - 0s - 930us/step - loss: 139.6288
Epoch 35/100
105/105 - 0s - 936us/step - loss: 140.4292
Epoch 36/100
105/105 - 0s - 926us/step - loss: 139.0403
Epoch 37/100
105/105 - 0s - 944us/step - loss: 138.7496
Epoch 38/100
105/105 - 0s - 949us/step - loss: 138.7551
Epoch 39/100
105/105 - 0s - 927us/step - loss: 139.9545
Epoch 40/100
105/105 - 0s - 936us/step - loss: 138.5918
Epoch 41/100
105/105 - 0s - 953us/step - loss: 138.3409
Epoch 42/100
105/105 - 0s - 954us/step - loss: 138.6015
Epoch 43/100
105/105 - 0s - 947us/step - loss: 138.7860
Epoch 44/100
105/105 - 0s - 920us/step - loss: 137.9851
Epoch 45/100
105/105 - 0s - 945us/step - loss: 138.8881
Epoch 46/100
105/105 - 0s - 930us/step - loss: 138.0528
Epoch 47/100
105/105 - 0s - 930us/step - loss: 138.5006
Epoch 48/100
105/105 - 0s - 927us/step - loss: 137.7033
Epoch 49/100
105/105 - 0s - 952us/step - loss: 137.5547
Epoch 50/100
105/105 - 0s - 927us/step - loss: 137.7532
Epoch 51/100
105/105 - 0s - 934us/step - loss: 138.1036
Epoch 52/100
105/105 - 0s - 1ms/step - loss: 137.6679
Epoch 53/100
105/105 - 0s - 933us/step - loss: 138.0593
Epoch 54/100
105/105 - 0s - 931us/step - loss: 137.3034
Epoch 55/100
105/105 - 0s - 927us/step - loss: 137.1253
Epoch 56/100
105/105 - 0s - 955us/step - loss: 136.8715
Epoch 57/100
105/105 - 0s - 950us/step - loss: 137.4464
Epoch 58/100
105/105 - 0s - 917us/step - loss: 137.4460
Epoch 59/100
105/105 - 0s - 929us/step - loss: 138.0307
Epoch 60/100
105/105 - 0s - 924us/step - loss: 137.2122
Epoch 61/100
105/105 - 0s - 940us/step - loss: 136.6909
Epoch 62/100
105/105 - 0s - 955us/step - loss: 137.7340
Epoch 63/100
105/105 - 0s - 933us/step - loss: 136.9815
Epoch 64/100
105/105 - 0s - 940us/step - loss: 136.3856
Epoch 65/100
105/105 - 0s - 934us/step - loss: 136.8681
Epoch 66/100
105/105 - 0s - 937us/step - loss: 137.2970
Epoch 67/100
105/105 - 0s - 911us/step - loss: 137.3678
Epoch 68/100
105/105 - 0s - 933us/step - loss: 137.0435
Epoch 69/100
105/105 - 0s - 954us/step - loss: 137.4710
Epoch 70/100
105/105 - 0s - 910us/step - loss: 137.2244
Epoch 71/100
105/105 - 0s - 933us/step - loss: 136.3153
Epoch 72/100
105/105 - 0s - 943us/step - loss: 136.8721
Epoch 73/100
105/105 - 0s - 942us/step - loss: 136.8908
Epoch 74/100
105/105 - 0s - 947us/step - loss: 136.6644
Epoch 75/100
105/105 - 0s - 908us/step - loss: 136.4026
Epoch 76/100
105/105 - 0s - 957us/step - loss: 136.7679
Epoch 77/100
105/105 - 0s - 943us/step - loss: 136.1936
Epoch 78/100
105/105 - 0s - 935us/step - loss: 136.4875
Epoch 79/100
105/105 - 0s - 936us/step - loss: 136.2766
Epoch 80/100
105/105 - 0s - 931us/step - loss: 135.6394
Epoch 81/100
105/105 - 0s - 923us/step - loss: 136.0260
Epoch 82/100
105/105 - 0s - 928us/step - loss: 136.0439
Epoch 83/100
105/105 - 0s - 942us/step - loss: 136.6114
Epoch 84/100
105/105 - 0s - 960us/step - loss: 136.0321
Epoch 85/100
105/105 - 0s - 955us/step - loss: 135.9856
Epoch 86/100
105/105 - 0s - 932us/step - loss: 135.9331
Epoch 87/100
105/105 - 0s - 947us/step - loss: 136.3871
Epoch 88/100
105/105 - 0s - 920us/step - loss: 136.0684
Epoch 89/100
105/105 - 0s - 926us/step - loss: 136.4154
Epoch 90/100
105/105 - 0s - 922us/step - loss: 135.9422
Epoch 91/100
105/105 - 0s - 931us/step - loss: 137.2035
Epoch 92/100
105/105 - 0s - 950us/step - loss: 137.1177
Epoch 93/100
105/105 - 0s - 952us/step - loss: 135.9473
Epoch 94/100
105/105 - 0s - 955us/step - loss: 136.0848
Epoch 95/100
105/105 - 0s - 921us/step - loss: 135.5438
Epoch 96/100
105/105 - 0s - 966us/step - loss: 135.8600
Epoch 97/100
105/105 - 0s - 967us/step - loss: 136.6341
Epoch 98/100
105/105 - 0s - 932us/step - loss: 136.6008
Epoch 99/100
105/105 - 0s - 934us/step - loss: 135.5287
Epoch 100/100
105/105 - 0s - 930us/step - loss: 136.7740
105/105 - 0s - 987us/step
Epoch 1/100

c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

105/105 - 1s - 6ms/step - loss: 1091.1373
Epoch 2/100
105/105 - 0s - 986us/step - loss: 564.9609
Epoch 3/100
105/105 - 0s - 964us/step - loss: 169.3603
Epoch 4/100
105/105 - 0s - 954us/step - loss: 156.3379
Epoch 5/100
105/105 - 0s - 936us/step - loss: 152.7558
Epoch 6/100
105/105 - 0s - 940us/step - loss: 150.4652
Epoch 7/100
105/105 - 0s - 945us/step - loss: 149.7189
Epoch 8/100
105/105 - 0s - 943us/step - loss: 148.2903
Epoch 9/100
105/105 - 0s - 930us/step - loss: 147.3830
Epoch 10/100
105/105 - 0s - 922us/step - loss: 147.2942
Epoch 11/100
105/105 - 0s - 934us/step - loss: 145.7395
Epoch 12/100
105/105 - 0s - 917us/step - loss: 146.2767
Epoch 13/100
105/105 - 0s - 937us/step - loss: 144.7742
Epoch 14/100
105/105 - 0s - 936us/step - loss: 145.3355
Epoch 15/100
105/105 - 0s - 946us/step - loss: 144.4118
Epoch 16/100
105/105 - 0s - 1ms/step - loss: 144.7543
Epoch 17/100
105/105 - 0s - 950us/step - loss: 143.9144
Epoch 18/100
105/105 - 0s - 918us/step - loss: 142.8355
Epoch 19/100
105/105 - 0s - 974us/step - loss: 142.7614
Epoch 20/100
105/105 - 0s - 930us/step - loss: 142.6801
Epoch 21/100
105/105 - 0s - 938us/step - loss: 142.1937
Epoch 22/100
105/105 - 0s - 934us/step - loss: 142.2869
Epoch 23/100
105/105 - 0s - 935us/step - loss: 141.3172
Epoch 24/100
105/105 - 0s - 923us/step - loss: 139.9186
Epoch 25/100
105/105 - 0s - 961us/step - loss: 142.1309
Epoch 26/100
105/105 - 0s - 929us/step - loss: 140.5929
Epoch 27/100
105/105 - 0s - 938us/step - loss: 140.8019
Epoch 28/100
105/105 - 0s - 927us/step - loss: 140.3885
Epoch 29/100
105/105 - 0s - 945us/step - loss: 139.8860
Epoch 30/100
105/105 - 0s - 954us/step - loss: 139.7146
Epoch 31/100
105/105 - 0s - 928us/step - loss: 139.7836
Epoch 32/100
105/105 - 0s - 949us/step - loss: 139.1630
Epoch 33/100
105/105 - 0s - 935us/step - loss: 138.8349
Epoch 34/100
105/105 - 0s - 936us/step - loss: 138.1900
Epoch 35/100
105/105 - 0s - 939us/step - loss: 138.3933
Epoch 36/100
105/105 - 0s - 927us/step - loss: 137.1853
Epoch 37/100
105/105 - 0s - 930us/step - loss: 137.4801
Epoch 38/100
105/105 - 0s - 923us/step - loss: 137.8156
Epoch 39/100
105/105 - 0s - 953us/step - loss: 137.1734
Epoch 40/100
105/105 - 0s - 929us/step - loss: 137.5152
Epoch 41/100
105/105 - 0s - 934us/step - loss: 136.8879
Epoch 42/100
105/105 - 0s - 923us/step - loss: 136.7682
Epoch 43/100
105/105 - 0s - 959us/step - loss: 136.3376
Epoch 44/100
105/105 - 0s - 912us/step - loss: 136.6632
Epoch 45/100
105/105 - 0s - 948us/step - loss: 136.5276
Epoch 46/100
105/105 - 0s - 944us/step - loss: 135.8304
Epoch 47/100
105/105 - 0s - 935us/step - loss: 135.7186
Epoch 48/100
105/105 - 0s - 931us/step - loss: 136.4475
Epoch 49/100
105/105 - 0s - 943us/step - loss: 135.3200
Epoch 50/100
105/105 - 0s - 917us/step - loss: 136.1944
Epoch 51/100
105/105 - 0s - 959us/step - loss: 136.5227
Epoch 52/100
105/105 - 0s - 934us/step - loss: 135.5915
Epoch 53/100
105/105 - 0s - 929us/step - loss: 135.4236
Epoch 54/100
105/105 - 0s - 919us/step - loss: 134.8424
Epoch 55/100
105/105 - 0s - 941us/step - loss: 135.0831
Epoch 56/100
105/105 - 0s - 934us/step - loss: 134.7806
Epoch 57/100
105/105 - 0s - 950us/step - loss: 134.9191
Epoch 58/100
105/105 - 0s - 926us/step - loss: 134.0497
Epoch 59/100
105/105 - 0s - 948us/step - loss: 134.2541
Epoch 60/100
105/105 - 0s - 954us/step - loss: 134.1844
Epoch 61/100
105/105 - 0s - 939us/step - loss: 133.7242
Epoch 62/100
105/105 - 0s - 943us/step - loss: 133.5108
Epoch 63/100
105/105 - 0s - 944us/step - loss: 133.7787
Epoch 64/100
105/105 - 0s - 928us/step - loss: 133.7403
Epoch 65/100
105/105 - 0s - 931us/step - loss: 133.0289
Epoch 66/100
105/105 - 0s - 923us/step - loss: 133.8450
Epoch 67/100
105/105 - 0s - 936us/step - loss: 132.7464
Epoch 68/100
105/105 - 0s - 925us/step - loss: 133.6708
Epoch 69/100
105/105 - 0s - 940us/step - loss: 133.1167
Epoch 70/100
105/105 - 0s - 931us/step - loss: 133.3965
Epoch 71/100
105/105 - 0s - 945us/step - loss: 134.2855
Epoch 72/100
105/105 - 0s - 988us/step - loss: 133.8102
Epoch 73/100
105/105 - 0s - 922us/step - loss: 132.3782
Epoch 74/100
105/105 - 0s - 942us/step - loss: 133.3530
Epoch 75/100
105/105 - 0s - 952us/step - loss: 133.1456
Epoch 76/100
105/105 - 0s - 944us/step - loss: 134.5001
Epoch 77/100
105/105 - 0s - 922us/step - loss: 132.1096
Epoch 78/100
105/105 - 0s - 931us/step - loss: 133.7394
Epoch 79/100
105/105 - 0s - 930us/step - loss: 133.0598
Epoch 80/100
105/105 - 0s - 936us/step - loss: 132.0405
Epoch 81/100
105/105 - 0s - 934us/step - loss: 132.9140
Epoch 82/100
105/105 - 0s - 948us/step - loss: 132.2589
Epoch 83/100
105/105 - 0s - 967us/step - loss: 132.3732
Epoch 84/100
105/105 - 0s - 939us/step - loss: 132.3062
Epoch 85/100
105/105 - 0s - 947us/step - loss: 132.2631
Epoch 86/100
105/105 - 0s - 941us/step - loss: 132.9538
Epoch 87/100
105/105 - 0s - 931us/step - loss: 132.3093
Epoch 88/100
105/105 - 0s - 927us/step - loss: 132.5590
Epoch 89/100
105/105 - 0s - 920us/step - loss: 131.7733
Epoch 90/100
105/105 - 0s - 949us/step - loss: 132.9707
Epoch 91/100
105/105 - 0s - 935us/step - loss: 132.3158
Epoch 92/100
105/105 - 0s - 916us/step - loss: 132.2089
Epoch 93/100
105/105 - 0s - 954us/step - loss: 131.0589
Epoch 94/100
105/105 - 0s - 936us/step - loss: 132.2636
Epoch 95/100
105/105 - 0s - 950us/step - loss: 132.7094
Epoch 96/100
105/105 - 0s - 925us/step - loss: 131.9207
Epoch 97/100
105/105 - 0s - 946us/step - loss: 132.3401
Epoch 98/100
105/105 - 0s - 906us/step - loss: 131.1457
Epoch 99/100
105/105 - 0s - 931us/step - loss: 131.7604
Epoch 100/100
105/105 - 0s - 936us/step - loss: 131.1811
105/105 - 0s - 974us/step
Result: 0.21 (0.04) MSE

In [176]:
pipeline.fit(X, Y)
prediction_train = pipeline.predict(X)
prediction_test = pipeline.predict(X_test)

Epoch 1/100

c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

210/210 - 1s - 4ms/step - loss: 718.6436
Epoch 2/100
210/210 - 0s - 821us/step - loss: 163.9879
Epoch 3/100
210/210 - 0s - 793us/step - loss: 156.7833
Epoch 4/100
210/210 - 0s - 802us/step - loss: 154.4097
Epoch 5/100
210/210 - 0s - 819us/step - loss: 153.0219
Epoch 6/100
210/210 - 0s - 799us/step - loss: 150.4883
Epoch 7/100
210/210 - 0s - 786us/step - loss: 149.2840
Epoch 8/100
210/210 - 0s - 812us/step - loss: 149.4263
Epoch 9/100
210/210 - 0s - 803us/step - loss: 147.2325
Epoch 10/100
210/210 - 0s - 814us/step - loss: 147.5950
Epoch 11/100
210/210 - 0s - 808us/step - loss: 146.9802
Epoch 12/100
210/210 - 0s - 802us/step - loss: 146.3658
Epoch 13/100
210/210 - 0s - 807us/step - loss: 146.4108
Epoch 14/100
210/210 - 0s - 806us/step - loss: 145.7020
Epoch 15/100
210/210 - 0s - 849us/step - loss: 145.2987
Epoch 16/100
210/210 - 0s - 834us/step - loss: 145.2878
Epoch 17/100
210/210 - 0s - 810us/step - loss: 146.0471
Epoch 18/100
210/210 - 0s - 790us/step - loss: 144.5098
Epoch 19/100
210/210 - 0s - 800us/step - loss: 144.2219
Epoch 20/100
210/210 - 0s - 814us/step - loss: 144.0434
Epoch 21/100
210/210 - 0s - 812us/step - loss: 144.9519
Epoch 22/100
210/210 - 0s - 807us/step - loss: 143.5193
Epoch 23/100
210/210 - 0s - 790us/step - loss: 142.4579
Epoch 24/100
210/210 - 0s - 806us/step - loss: 144.0634
Epoch 25/100
210/210 - 0s - 797us/step - loss: 143.2813
Epoch 26/100
210/210 - 0s - 795us/step - loss: 143.5565
Epoch 27/100
210/210 - 0s - 812us/step - loss: 143.4597
Epoch 28/100
210/210 - 0s - 806us/step - loss: 142.4407
Epoch 29/100
210/210 - 0s - 799us/step - loss: 143.0740
Epoch 30/100
210/210 - 0s - 825us/step - loss: 141.8852
Epoch 31/100
210/210 - 0s - 811us/step - loss: 142.0995
Epoch 32/100
210/210 - 0s - 803us/step - loss: 141.8091
Epoch 33/100
210/210 - 0s - 832us/step - loss: 142.4794
Epoch 34/100
210/210 - 0s - 809us/step - loss: 142.6826
Epoch 35/100
210/210 - 0s - 833us/step - loss: 142.1185
Epoch 36/100
210/210 - 0s - 805us/step - loss: 142.4507
Epoch 37/100
210/210 - 0s - 833us/step - loss: 142.5309
Epoch 38/100
210/210 - 0s - 799us/step - loss: 141.2557
Epoch 39/100
210/210 - 0s - 794us/step - loss: 142.3034
Epoch 40/100
210/210 - 0s - 815us/step - loss: 141.9914
Epoch 41/100
210/210 - 0s - 866us/step - loss: 142.2223
Epoch 42/100
210/210 - 0s - 790us/step - loss: 142.2442
Epoch 43/100
210/210 - 0s - 788us/step - loss: 142.0441
Epoch 44/100
210/210 - 0s - 804us/step - loss: 141.7789
Epoch 45/100
210/210 - 0s - 789us/step - loss: 141.8174
Epoch 46/100
210/210 - 0s - 806us/step - loss: 142.8123
Epoch 47/100
210/210 - 0s - 803us/step - loss: 141.6546
Epoch 48/100
210/210 - 0s - 804us/step - loss: 141.9353
Epoch 49/100
210/210 - 0s - 789us/step - loss: 141.3506
Epoch 50/100
210/210 - 0s - 817us/step - loss: 141.5783
Epoch 51/100
210/210 - 0s - 840us/step - loss: 142.1437
Epoch 52/100
210/210 - 0s - 813us/step - loss: 141.7721
Epoch 53/100
210/210 - 0s - 795us/step - loss: 141.2232
Epoch 54/100
210/210 - 0s - 843us/step - loss: 140.9838
Epoch 55/100
210/210 - 0s - 815us/step - loss: 141.5959
Epoch 56/100
210/210 - 0s - 818us/step - loss: 142.2437
Epoch 57/100
210/210 - 0s - 830us/step - loss: 141.9068
Epoch 58/100
210/210 - 0s - 804us/step - loss: 141.0284
Epoch 59/100
210/210 - 0s - 797us/step - loss: 141.4201
Epoch 60/100
210/210 - 0s - 806us/step - loss: 141.6082
Epoch 61/100
210/210 - 0s - 820us/step - loss: 141.4294
Epoch 62/100
210/210 - 0s - 812us/step - loss: 141.3880
Epoch 63/100
210/210 - 0s - 799us/step - loss: 141.0680
Epoch 64/100
210/210 - 0s - 814us/step - loss: 141.4916
Epoch 65/100
210/210 - 0s - 810us/step - loss: 141.7697
Epoch 66/100
210/210 - 0s - 799us/step - loss: 141.2577
Epoch 67/100
210/210 - 0s - 825us/step - loss: 140.8449
Epoch 68/100
210/210 - 0s - 809us/step - loss: 141.1301
Epoch 69/100
210/210 - 0s - 819us/step - loss: 140.9847
Epoch 70/100
210/210 - 0s - 807us/step - loss: 140.9247
Epoch 71/100
210/210 - 0s - 800us/step - loss: 141.1049
Epoch 72/100
210/210 - 0s - 799us/step - loss: 140.7722
Epoch 73/100
210/210 - 0s - 843us/step - loss: 140.4983
Epoch 74/100
210/210 - 0s - 807us/step - loss: 142.2184
Epoch 75/100
210/210 - 0s - 822us/step - loss: 140.9012
Epoch 76/100
210/210 - 0s - 806us/step - loss: 139.7454
Epoch 77/100
210/210 - 0s - 810us/step - loss: 141.0218
Epoch 78/100
210/210 - 0s - 801us/step - loss: 140.3365
Epoch 79/100
210/210 - 0s - 790us/step - loss: 141.2522
Epoch 80/100
210/210 - 0s - 813us/step - loss: 142.3514
Epoch 81/100
210/210 - 0s - 815us/step - loss: 141.1617
Epoch 82/100
210/210 - 0s - 796us/step - loss: 140.3175
Epoch 83/100
210/210 - 0s - 812us/step - loss: 140.9113
Epoch 84/100
210/210 - 0s - 785us/step - loss: 140.5179
Epoch 85/100
210/210 - 0s - 822us/step - loss: 140.8561
Epoch 86/100
210/210 - 0s - 810us/step - loss: 141.5403
Epoch 87/100
210/210 - 0s - 801us/step - loss: 140.5372
Epoch 88/100
210/210 - 0s - 798us/step - loss: 141.0960
Epoch 89/100
210/210 - 0s - 809us/step - loss: 140.7555
Epoch 90/100
210/210 - 0s - 832us/step - loss: 140.8936
Epoch 91/100
210/210 - 0s - 786us/step - loss: 139.7273
Epoch 92/100
210/210 - 0s - 805us/step - loss: 141.6677
Epoch 93/100
210/210 - 0s - 820us/step - loss: 140.0335
Epoch 94/100
210/210 - 0s - 818us/step - loss: 140.6835
Epoch 95/100
210/210 - 0s - 807us/step - loss: 140.7413
Epoch 96/100
210/210 - 0s - 795us/step - loss: 140.5771
Epoch 97/100
210/210 - 0s - 812us/step - loss: 140.7592
Epoch 98/100
210/210 - 0s - 825us/step - loss: 140.8228
Epoch 99/100
210/210 - 0s - 801us/step - loss: 140.8225
Epoch 100/100
210/210 - 0s - 795us/step - loss: 140.6731
210/210 - 0s - 666us/step
53/53 - 0s - 788us/step

Generate new input files for the training and test data with predicted age

In [177]:
# Create a data frame with PassengerId and predicted age
df_age_pred = pd.DataFrame({
    'PassengerId': df_age_nan.index,
    'Age_pred': prediction_test.astype(int)
})
df_age_pred.set_index('PassengerId', inplace=True)
   

# Add column with predicted age to the dataframe with all data (dfa)

dfa2 = pd.concat([df_train, df_test])
dfa_pred = pd.concat([dfa2, df_age_pred], axis=1)   

# Update Age column with prediction where nan and remove Age_pred
dfa_pred['Age'] = np.where(pd.isnull(dfa_pred['Age']), dfa_pred['Age_pred'] , dfa_pred['Age'])
dfa_pred = dfa_pred.drop(['Age_pred'], axis=1)

# Create new files
l = len(df_train)
df_train2 = dfa_pred[0:l] 
df_test2 = dfa_pred[l:] 
df_test2 = df_test2.drop(['Survived'], axis=1)

df_train2.to_csv('train-age-predicted.csv')
df_test2.to_csv('test-age-predicted.csv')

# Part 3 - Wrangle, prepare, cleanse the titanic data manually

Re-read data, drop the Cabin and Ticket features

In [178]:
train_df = pd.read_csv('../data/train.csv')
test_df = pd.read_csv('../data/test.csv')
train_df = train_df.drop(['Ticket', 'Cabin'], axis=1)
test_df = test_df.drop(['Ticket', 'Cabin'], axis=1)
combine = [train_df, test_df]

Creating new feature extracting from existing ...

In [179]:
for dataset in combine:
    dataset['Title'] = dataset.Name.str.extract(' ([A-Za-z]+)\.', expand=False)

for dataset in combine:
    dataset['Title'] = dataset['Title'].replace(['Lady', 'Countess','Capt', 'Col',\
 	'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')

    dataset['Title'] = dataset['Title'].replace('Mlle', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Ms', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Mme', 'Mrs')
    
train_df[['Title', 'Survived']].groupby(['Title'], as_index=False).mean()

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
C:\Users\alexandre.karneff\AppData\Local\Temp\ipykernel_18152\1402529983.py:2: SyntaxWarning: invalid escape sequence '\.'
  dataset['Title'] = dataset.Name.str.extract(' ([A-Za-z]+)\.', expand=False)

    Title  Survived
0  Master  0.575000
1    Miss  0.702703
2      Mr  0.156673
3     Mrs  0.793651
4    Rare  0.347826

In [180]:
train_df.Title.value_counts()

Title
Mr        517
Miss      185
Mrs       126
Master     40
Rare       23
Name: count, dtype: int64

In [181]:
# convert the categorical titles to ordinal.
title_mapping = {"Mr": 1, "Miss": 2, "Mrs": 3, "Master": 4, "Rare": 5}
for dataset in combine:
    dataset['Title'] = dataset['Title'].map(title_mapping)
    dataset['Title'] = dataset['Title'].fillna(0)

# Drop Name feature
train_df = train_df.drop(['Name'], axis=1)
test_df = test_df.drop(['Name'], axis=1)
combine = [train_df, test_df]

In [182]:
for dataset in combine:
    dataset['Sex'] = dataset['Sex'].map( {'female': 1, 'male': 0} ).astype(int)

In [183]:
train_df.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title
0,1,0,3,0,22.0,1,0,7.2500,S,1
1,2,1,1,1,38.0,1,0,71.2833,C,3
2,3,1,3,1,26.0,0,0,7.9250,S,2
3,4,1,1,1,35.0,1,0,53.1000,S,3
4,5,0,3,0,35.0,0,0,8.0500,S,1
5,6,0,3,0,NaN,0,0,8.4583,Q,1
6,7,0,1,0,54.0,0,0,51.8625,S,1
7,8,0,3,0,2.0,3,1,21.0750,S,4
8,9,1,3,1,27.0,0,2,11.1333,S,3
9,10,1,2,1,14.0,1,0,30.0708,C,3

In [184]:
guess_ages = np.zeros((2,3))
for dataset in combine:
    for i in range(0, 2):
        for j in range(0, 3):
            guess_df = dataset[(dataset['Sex'] == i) & \
                                  (dataset['Pclass'] == j+1)]['Age'].dropna()

            age_guess = guess_df.median()

            # Convert random age float to nearest .5 age
            guess_ages[i,j] = int( age_guess/0.5 + 0.5 ) * 0.5
            
    for i in range(0, 2):
        for j in range(0, 3):
            dataset.loc[ (dataset.Age.isnull()) & (dataset.Sex == i) & (dataset.Pclass == j+1),\
                    'Age'] = guess_ages[i,j]

    dataset['Age'] = dataset['Age'].astype(int)

In [185]:
for dataset in combine:    
    dataset.loc[ dataset['Age'] <= 16, 'Age'] = 0
    dataset.loc[(dataset['Age'] > 16) & (dataset['Age'] <= 32), 'Age'] = 1
    dataset.loc[(dataset['Age'] > 32) & (dataset['Age'] <= 48), 'Age'] = 2
    dataset.loc[(dataset['Age'] > 48) & (dataset['Age'] <= 64), 'Age'] = 3
    dataset.loc[ dataset['Age'] > 64, 'Age'] = 4

train_df.head(10)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title
0,1,0,3,0,1,1,0,7.2500,S,1
1,2,1,1,1,2,1,0,71.2833,C,3
2,3,1,3,1,1,0,0,7.9250,S,2
3,4,1,1,1,2,1,0,53.1000,S,3
4,5,0,3,0,2,0,0,8.0500,S,1
5,6,0,3,0,1,0,0,8.4583,Q,1
6,7,0,1,0,3,0,0,51.8625,S,1
7,8,0,3,0,0,3,1,21.0750,S,4
8,9,1,3,1,1,0,2,11.1333,S,3
9,10,1,2,1,0,1,0,30.0708,C,3

In [186]:
train_df.Age.value_counts()

Age
1    495
2    216
0    100
3     69
4     11
Name: count, dtype: int64

Create new feature for FamilySize which combines Parch and SibSp

In [187]:
combine = [train_df, test_df]
for dataset in combine:
    dataset['FamilySize'] = dataset['SibSp'] + dataset['Parch'] + 1

train_df[['FamilySize', 'Survived']].groupby(['FamilySize'], as_index=False).mean().sort_values(by='Survived', ascending=False)

   FamilySize  Survived
3           4  0.724138
2           3  0.578431
1           2  0.552795
6           7  0.333333
0           1  0.303538
4           5  0.200000
5           6  0.136364
7           8  0.000000
8          11  0.000000

In [188]:
for dataset in combine:
    dataset['IsAlone'] = 0
    dataset.loc[dataset['FamilySize'] == 1, 'IsAlone'] = 1

train_df[['IsAlone', 'Survived']].groupby(['IsAlone'], as_index=False).mean()

   IsAlone  Survived
0        0  0.505650
1        1  0.303538

Drop Parch, SibSp, and FamilySize features in favor of IsAlone

In [189]:
train_df = train_df.drop(['Parch', 'SibSp', 'FamilySize'], axis=1)
test_df = test_df.drop(['Parch', 'SibSp', 'FamilySize'], axis=1)
combine = [train_df, test_df]

Create an artificial feature combining Pclass and Age

In [190]:
for dataset in combine:
    dataset['Age*Class'] = dataset.Age * dataset.Pclass

train_df.loc[:, ['Age*Class', 'Age', 'Pclass']].head(10)

   Age*Class  Age  Pclass
0          3    1       3
1          2    2       1
2          3    1       3
3          2    2       1
4          6    2       3
5          3    1       3
6          3    3       1
7          0    0       3
8          3    1       3
9          0    0       2

Completing a categorical feature

In [191]:
freq_port = train_df.Embarked.dropna().mode()[0]

for dataset in combine:
    dataset['Embarked'] = dataset['Embarked'].fillna(freq_port)
    
for dataset in combine:
    dataset['Embarked'] = dataset['Embarked'].map( {'S': 0, 'C': 1, 'Q': 2} ).astype(int)

test_df['Fare'].fillna(test_df['Fare'].dropna().median(), inplace=True)

C:\Users\alexandre.karneff\AppData\Local\Temp\ipykernel_18152\1559063093.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_df['Fare'].fillna(test_df['Fare'].dropna().median(), inplace=True)

Fare feature to ordinal values based on the FareBand

In [192]:
for dataset in combine:
    dataset.loc[ dataset['Fare'] <= 7.91, 'Fare'] = 0
    dataset.loc[(dataset['Fare'] > 7.91) & (dataset['Fare'] <= 14.454), 'Fare'] = 1
    dataset.loc[(dataset['Fare'] > 14.454) & (dataset['Fare'] <= 31), 'Fare']   = 2
    dataset.loc[ dataset['Fare'] > 31, 'Fare'] = 3
    dataset['Fare'] = dataset['Fare'].astype(int)

combine = [train_df, test_df]

Save wrangled training and test data to files

In [193]:
train_df.to_csv('../data/train-wrangled.csv',index=False)
test_df.to_csv('../data/test-wrangled.csv',index=False)

In [194]:
# Input files
file_train='../data/train-wrangled.csv'
file_test='../data/test-wrangled.csv'

# read training data
train_df = pd.read_csv(file_train,index_col='PassengerId')

In [195]:
train_df.columns.values

array(['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Title',
       'IsAlone', 'Age*Class'], dtype=object)

In [196]:
# Show the shape
train_df.shape

(891, 9)

In [197]:
# preview the training dara
train_df.head(20)

,Survived,Pclass,Sex,Age,Fare,Embarked,Title,IsAlone,Age*Class
PassengerId,,,,,,,,,
1,0,3,0,1,0,0,1,0,3
2,1,1,1,2,3,1,3,0,2
3,1,3,1,1,1,0,2,1,3
4,1,1,1,2,3,0,3,0,2
5,0,3,0,2,1,0,1,1,6
6,0,3,0,1,1,2,1,1,3
7,0,1,0,3,3,0,1,1,3
8,0,3,0,0,2,0,4,0,0
9,1,3,1,1,1,0,3,0,3
10,1,2,1,0,2,1,3,0,0
11,1,3,1,0,2,0,2,0,0
12,1,1,1,3,2,0,2,1,3
13,0,3,0,1,1,0,1,1,3
14,0,3,0,2,3,0,1,0,6
15,0,3,1,0,0,0,2,1,0
16,1,2,1,3,2,0,3,1,6
17,0,3,0,0,2,2,4,0,0
18,1,2,0,1,1,0,1,1,2
19,0,3,1,1,2,0,3,0,3
20,1,3,1,1,0,1,3,1,3

In [198]:
# Show that there isn't any NaN data 
train_df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age          0
Fare         0
Embarked     0
Title        0
IsAlone      0
Age*Class    0
dtype: int64

In [199]:
# X contains all columns except 'Survived'  
X = train_df.drop(['Survived'], axis=1).values.astype(float)

# It is almost always a good idea to perform some scaling of input values when using neural network models (jb).

scale = StandardScaler()
X = scale.fit_transform(X)

# Y is just the 'Survived' column
Y = train_df['Survived'].values

In [200]:
train_df.Age.value_counts()

Age
1    495
2    216
0    100
3     69
4     11
Name: count, dtype: int64

In [201]:
run_gridsearch = False

if run_gridsearch:
    
    start_time = time.time()
    if verbose: print (time.strftime( "%H:%M:%S " + "GridSearch started ... " ) )
    optimizers = ['rmsprop', 'adam']
    inits = ['glorot_uniform', 'normal', 'uniform']
    epochs = [50, 100, 200, 400]
    batches = [5, 10, 20]
    
    model = KerasClassifier(build_fn=create_model, verbose=verbose)
    
    param_grid = dict(optimizer=optimizers, epochs=epochs, batch_size=batches, init=inits)
    grid = GridSearchCV(estimator=model, param_grid=param_grid)
    grid_result = grid.fit(X, Y)
    
    # summarize results
    print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
    means = grid_result.cv_results_['mean_test_score']
    stds = grid_result.cv_results_['std_test_score']
    params = grid_result.cv_results_['params']
    if verbose: 
        for mean, stdev, param in zip(means, stds, params):
            print("%f (%f) with: %r" % (mean, stdev, param))
        elapsed_time = time.time() - start_time  
        print ("Time elapsed: ",timedelta(seconds=elapsed_time))
        
    best_epochs = grid_result.best_params_['epochs']
    best_batch_size = grid_result.best_params_['batch_size']
    best_init = grid_result.best_params_['init']
    best_optimizer = grid_result.best_params_['optimizer']
    
else:
    # pre-selected paramters
    best_epochs = 200
    best_batch_size = 5
    best_init = 'glorot_uniform'
    best_optimizer = 'rmsprop'

In [202]:
# Create a classifier with best parameters
model_pred = KerasClassifier(build_fn=create_model, optimizer=best_optimizer, init=best_init, epochs=best_epochs, batch_size=best_batch_size, verbose=verbose)
model_pred.fit(X, Y)

# Read test data
test_df = pd.read_csv(file_test,index_col='PassengerId')

# Create X_test
X_test = test_df.values.astype(float)
# Scaling
X_test = scale.transform(X_test)

# Predict 'Survived'
prediction = model_pred.predict(X_test)

**Create model with optimizer: adam; init: glorot_uniform
Epoch 1/200

c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\alexandre.karneff\Documents\GitHub\alexandre.karneff\envWorkshop\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

179/179 - 1s - 4ms/step - accuracy: 0.6869 - loss: 0.6195
Epoch 2/200
179/179 - 0s - 854us/step - accuracy: 0.7688 - loss: 0.5183
Epoch 3/200
179/179 - 0s - 964us/step - accuracy: 0.8114 - loss: 0.4726
Epoch 4/200
179/179 - 0s - 865us/step - accuracy: 0.8171 - loss: 0.4457
Epoch 5/200
179/179 - 0s - 877us/step - accuracy: 0.8215 - loss: 0.4270
Epoch 6/200
179/179 - 0s - 863us/step - accuracy: 0.8204 - loss: 0.4172
Epoch 7/200
179/179 - 0s - 875us/step - accuracy: 0.8283 - loss: 0.4088
Epoch 8/200
179/179 - 0s - 848us/step - accuracy: 0.8350 - loss: 0.4048
Epoch 9/200
179/179 - 0s - 875us/step - accuracy: 0.8373 - loss: 0.4022
Epoch 10/200
179/179 - 0s - 858us/step - accuracy: 0.8294 - loss: 0.3990
Epoch 11/200
179/179 - 0s - 892us/step - accuracy: 0.8339 - loss: 0.3975
Epoch 12/200
179/179 - 0s - 843us/step - accuracy: 0.8328 - loss: 0.3973
Epoch 13/200
179/179 - 0s - 874us/step - accuracy: 0.8316 - loss: 0.3952
Epoch 14/200
179/179 - 0s - 866us/step - accuracy: 0.8305 - loss: 0.3930
Epoch 15/200
179/179 - 0s - 871us/step - accuracy: 0.8328 - loss: 0.3901
Epoch 16/200
179/179 - 0s - 866us/step - accuracy: 0.8350 - loss: 0.3900
Epoch 17/200
179/179 - 0s - 876us/step - accuracy: 0.8361 - loss: 0.3909
Epoch 18/200
179/179 - 0s - 867us/step - accuracy: 0.8384 - loss: 0.3875
Epoch 19/200
179/179 - 0s - 859us/step - accuracy: 0.8339 - loss: 0.3881
Epoch 20/200
179/179 - 0s - 876us/step - accuracy: 0.8373 - loss: 0.3873
Epoch 21/200
179/179 - 0s - 862us/step - accuracy: 0.8339 - loss: 0.3855
Epoch 22/200
179/179 - 0s - 853us/step - accuracy: 0.8373 - loss: 0.3844
Epoch 23/200
179/179 - 0s - 867us/step - accuracy: 0.8361 - loss: 0.3824
Epoch 24/200
179/179 - 0s - 863us/step - accuracy: 0.8373 - loss: 0.3814
Epoch 25/200
179/179 - 0s - 863us/step - accuracy: 0.8361 - loss: 0.3823
Epoch 26/200
179/179 - 0s - 863us/step - accuracy: 0.8328 - loss: 0.3809
Epoch 27/200
179/179 - 0s - 856us/step - accuracy: 0.8418 - loss: 0.3804
Epoch 28/200
179/179 - 0s - 949us/step - accuracy: 0.8361 - loss: 0.3781
Epoch 29/200
179/179 - 0s - 886us/step - accuracy: 0.8384 - loss: 0.3777
Epoch 30/200
179/179 - 0s - 850us/step - accuracy: 0.8328 - loss: 0.3780
Epoch 31/200
179/179 - 0s - 872us/step - accuracy: 0.8272 - loss: 0.3785
Epoch 32/200
179/179 - 0s - 848us/step - accuracy: 0.8361 - loss: 0.3763
Epoch 33/200
179/179 - 0s - 884us/step - accuracy: 0.8406 - loss: 0.3750
Epoch 34/200
179/179 - 0s - 855us/step - accuracy: 0.8328 - loss: 0.3738
Epoch 35/200
179/179 - 0s - 862us/step - accuracy: 0.8384 - loss: 0.3738
Epoch 36/200
179/179 - 0s - 851us/step - accuracy: 0.8361 - loss: 0.3737
Epoch 37/200
179/179 - 0s - 866us/step - accuracy: 0.8418 - loss: 0.3722
Epoch 38/200
179/179 - 0s - 857us/step - accuracy: 0.8361 - loss: 0.3748
Epoch 39/200
179/179 - 0s - 878us/step - accuracy: 0.8350 - loss: 0.3721
Epoch 40/200
179/179 - 0s - 975us/step - accuracy: 0.8418 - loss: 0.3714
Epoch 41/200
179/179 - 0s - 962us/step - accuracy: 0.8429 - loss: 0.3716
Epoch 42/200
179/179 - 0s - 860us/step - accuracy: 0.8361 - loss: 0.3686
Epoch 43/200
179/179 - 0s - 868us/step - accuracy: 0.8328 - loss: 0.3737
Epoch 44/200
179/179 - 0s - 871us/step - accuracy: 0.8339 - loss: 0.3682
Epoch 45/200
179/179 - 0s - 873us/step - accuracy: 0.8305 - loss: 0.3681
Epoch 46/200
179/179 - 0s - 853us/step - accuracy: 0.8305 - loss: 0.3687
Epoch 47/200
179/179 - 0s - 855us/step - accuracy: 0.8406 - loss: 0.3683
Epoch 48/200
179/179 - 0s - 867us/step - accuracy: 0.8395 - loss: 0.3677
Epoch 49/200
179/179 - 0s - 857us/step - accuracy: 0.8395 - loss: 0.3671
Epoch 50/200
179/179 - 0s - 872us/step - accuracy: 0.8395 - loss: 0.3709
Epoch 51/200
179/179 - 0s - 917us/step - accuracy: 0.8406 - loss: 0.3687
Epoch 52/200
179/179 - 0s - 856us/step - accuracy: 0.8328 - loss: 0.3668
Epoch 53/200
179/179 - 0s - 886us/step - accuracy: 0.8406 - loss: 0.3670
Epoch 54/200
179/179 - 0s - 859us/step - accuracy: 0.8395 - loss: 0.3674
Epoch 55/200
179/179 - 0s - 880us/step - accuracy: 0.8429 - loss: 0.3644
Epoch 56/200
179/179 - 0s - 861us/step - accuracy: 0.8440 - loss: 0.3652
Epoch 57/200
179/179 - 0s - 855us/step - accuracy: 0.8406 - loss: 0.3634
Epoch 58/200
179/179 - 0s - 860us/step - accuracy: 0.8474 - loss: 0.3627
Epoch 59/200
179/179 - 0s - 872us/step - accuracy: 0.8361 - loss: 0.3652
Epoch 60/200
179/179 - 0s - 936us/step - accuracy: 0.8406 - loss: 0.3632
Epoch 61/200
179/179 - 0s - 891us/step - accuracy: 0.8373 - loss: 0.3627
Epoch 62/200
179/179 - 0s - 864us/step - accuracy: 0.8406 - loss: 0.3649
Epoch 63/200
179/179 - 0s - 860us/step - accuracy: 0.8384 - loss: 0.3622
Epoch 64/200
179/179 - 0s - 855us/step - accuracy: 0.8373 - loss: 0.3610
Epoch 65/200
179/179 - 0s - 853us/step - accuracy: 0.8316 - loss: 0.3627
Epoch 66/200
179/179 - 0s - 855us/step - accuracy: 0.8373 - loss: 0.3632
Epoch 67/200
179/179 - 0s - 873us/step - accuracy: 0.8395 - loss: 0.3609
Epoch 68/200
179/179 - 0s - 871us/step - accuracy: 0.8328 - loss: 0.3633
Epoch 69/200
179/179 - 0s - 864us/step - accuracy: 0.8361 - loss: 0.3628
Epoch 70/200
179/179 - 0s - 853us/step - accuracy: 0.8395 - loss: 0.3596
Epoch 71/200
179/179 - 0s - 866us/step - accuracy: 0.8418 - loss: 0.3586
Epoch 72/200
179/179 - 0s - 967us/step - accuracy: 0.8406 - loss: 0.3618
Epoch 73/200
179/179 - 0s - 946us/step - accuracy: 0.8429 - loss: 0.3599
Epoch 74/200
179/179 - 0s - 863us/step - accuracy: 0.8395 - loss: 0.3598
Epoch 75/200
179/179 - 0s - 857us/step - accuracy: 0.8395 - loss: 0.3581
Epoch 76/200
179/179 - 0s - 854us/step - accuracy: 0.8451 - loss: 0.3605
Epoch 77/200
179/179 - 0s - 857us/step - accuracy: 0.8406 - loss: 0.3598
Epoch 78/200
179/179 - 0s - 857us/step - accuracy: 0.8440 - loss: 0.3606
Epoch 79/200
179/179 - 0s - 856us/step - accuracy: 0.8361 - loss: 0.3567
Epoch 80/200
179/179 - 0s - 859us/step - accuracy: 0.8440 - loss: 0.3596
Epoch 81/200
179/179 - 0s - 862us/step - accuracy: 0.8406 - loss: 0.3585
Epoch 82/200
179/179 - 0s - 868us/step - accuracy: 0.8462 - loss: 0.3551
Epoch 83/200
179/179 - 0s - 871us/step - accuracy: 0.8384 - loss: 0.3585
Epoch 84/200
179/179 - 0s - 847us/step - accuracy: 0.8395 - loss: 0.3550
Epoch 85/200
179/179 - 0s - 870us/step - accuracy: 0.8395 - loss: 0.3573
Epoch 86/200
179/179 - 0s - 863us/step - accuracy: 0.8384 - loss: 0.3568
Epoch 87/200
179/179 - 0s - 886us/step - accuracy: 0.8418 - loss: 0.3546
Epoch 88/200
179/179 - 0s - 837us/step - accuracy: 0.8395 - loss: 0.3586
Epoch 89/200
179/179 - 0s - 871us/step - accuracy: 0.8440 - loss: 0.3560
Epoch 90/200
179/179 - 0s - 854us/step - accuracy: 0.8440 - loss: 0.3546
Epoch 91/200
179/179 - 0s - 865us/step - accuracy: 0.8451 - loss: 0.3536
Epoch 92/200
179/179 - 0s - 859us/step - accuracy: 0.8406 - loss: 0.3567
Epoch 93/200
179/179 - 0s - 897us/step - accuracy: 0.8350 - loss: 0.3529
Epoch 94/200
179/179 - 0s - 866us/step - accuracy: 0.8418 - loss: 0.3539
Epoch 95/200
179/179 - 0s - 894us/step - accuracy: 0.8440 - loss: 0.3552
Epoch 96/200
179/179 - 0s - 870us/step - accuracy: 0.8395 - loss: 0.3537
Epoch 97/200
179/179 - 0s - 868us/step - accuracy: 0.8462 - loss: 0.3553
Epoch 98/200
179/179 - 0s - 859us/step - accuracy: 0.8406 - loss: 0.3552
Epoch 99/200
179/179 - 0s - 875us/step - accuracy: 0.8429 - loss: 0.3560
Epoch 100/200
179/179 - 0s - 850us/step - accuracy: 0.8328 - loss: 0.3539
Epoch 101/200
179/179 - 0s - 856us/step - accuracy: 0.8440 - loss: 0.3515
Epoch 102/200
179/179 - 0s - 870us/step - accuracy: 0.8395 - loss: 0.3540
Epoch 103/200
179/179 - 0s - 863us/step - accuracy: 0.8496 - loss: 0.3528
Epoch 104/200
179/179 - 0s - 856us/step - accuracy: 0.8462 - loss: 0.3517
Epoch 105/200
179/179 - 0s - 867us/step - accuracy: 0.8418 - loss: 0.3553
Epoch 106/200
179/179 - 0s - 860us/step - accuracy: 0.8474 - loss: 0.3508
Epoch 107/200
179/179 - 0s - 869us/step - accuracy: 0.8451 - loss: 0.3515
Epoch 108/200
179/179 - 0s - 852us/step - accuracy: 0.8440 - loss: 0.3540
Epoch 109/200
179/179 - 0s - 884us/step - accuracy: 0.8507 - loss: 0.3495
Epoch 110/200
179/179 - 0s - 855us/step - accuracy: 0.8406 - loss: 0.3520
Epoch 111/200
179/179 - 0s - 843us/step - accuracy: 0.8418 - loss: 0.3522
Epoch 112/200
179/179 - 0s - 861us/step - accuracy: 0.8474 - loss: 0.3492
Epoch 113/200
179/179 - 0s - 875us/step - accuracy: 0.8395 - loss: 0.3522
Epoch 114/200
179/179 - 0s - 856us/step - accuracy: 0.8541 - loss: 0.3499
Epoch 115/200
179/179 - 0s - 876us/step - accuracy: 0.8485 - loss: 0.3522
Epoch 116/200
179/179 - 0s - 853us/step - accuracy: 0.8440 - loss: 0.3487
Epoch 117/200
179/179 - 0s - 865us/step - accuracy: 0.8451 - loss: 0.3496
Epoch 118/200
179/179 - 0s - 910us/step - accuracy: 0.8406 - loss: 0.3509
Epoch 119/200
179/179 - 0s - 854us/step - accuracy: 0.8451 - loss: 0.3517
Epoch 120/200
179/179 - 0s - 851us/step - accuracy: 0.8418 - loss: 0.3508
Epoch 121/200
179/179 - 0s - 886us/step - accuracy: 0.8395 - loss: 0.3500
Epoch 122/200
179/179 - 0s - 872us/step - accuracy: 0.8462 - loss: 0.3483
Epoch 123/200
179/179 - 0s - 891us/step - accuracy: 0.8496 - loss: 0.3483
Epoch 124/200
179/179 - 0s - 873us/step - accuracy: 0.8384 - loss: 0.3523
Epoch 125/200
179/179 - 0s - 864us/step - accuracy: 0.8429 - loss: 0.3481
Epoch 126/200
179/179 - 0s - 854us/step - accuracy: 0.8451 - loss: 0.3487
Epoch 127/200
179/179 - 0s - 853us/step - accuracy: 0.8462 - loss: 0.3507
Epoch 128/200
179/179 - 0s - 861us/step - accuracy: 0.8384 - loss: 0.3464
Epoch 129/200
179/179 - 0s - 866us/step - accuracy: 0.8429 - loss: 0.3493
Epoch 130/200
179/179 - 0s - 859us/step - accuracy: 0.8462 - loss: 0.3464
Epoch 131/200
179/179 - 0s - 871us/step - accuracy: 0.8440 - loss: 0.3492
Epoch 132/200
179/179 - 0s - 853us/step - accuracy: 0.8429 - loss: 0.3487
Epoch 133/200
179/179 - 0s - 888us/step - accuracy: 0.8418 - loss: 0.3466
Epoch 134/200
179/179 - 0s - 849us/step - accuracy: 0.8485 - loss: 0.3470
Epoch 135/200
179/179 - 0s - 881us/step - accuracy: 0.8384 - loss: 0.3473
Epoch 136/200
179/179 - 0s - 872us/step - accuracy: 0.8406 - loss: 0.3493
Epoch 137/200
179/179 - 0s - 849us/step - accuracy: 0.8406 - loss: 0.3471
Epoch 138/200
179/179 - 0s - 861us/step - accuracy: 0.8440 - loss: 0.3469
Epoch 139/200
179/179 - 0s - 886us/step - accuracy: 0.8451 - loss: 0.3462
Epoch 140/200
179/179 - 0s - 860us/step - accuracy: 0.8429 - loss: 0.3474
Epoch 141/200
179/179 - 0s - 1ms/step - accuracy: 0.8485 - loss: 0.3461
Epoch 142/200
179/179 - 0s - 876us/step - accuracy: 0.8496 - loss: 0.3457
Epoch 143/200
179/179 - 0s - 889us/step - accuracy: 0.8496 - loss: 0.3461
Epoch 144/200
179/179 - 0s - 873us/step - accuracy: 0.8429 - loss: 0.3459
Epoch 145/200
179/179 - 0s - 882us/step - accuracy: 0.8451 - loss: 0.3470
Epoch 146/200
179/179 - 0s - 874us/step - accuracy: 0.8474 - loss: 0.3464
Epoch 147/200
179/179 - 0s - 876us/step - accuracy: 0.8462 - loss: 0.3451
Epoch 148/200
179/179 - 0s - 875us/step - accuracy: 0.8507 - loss: 0.3437
Epoch 149/200
179/179 - 0s - 872us/step - accuracy: 0.8496 - loss: 0.3423
Epoch 150/200
179/179 - 0s - 866us/step - accuracy: 0.8451 - loss: 0.3431
Epoch 151/200
179/179 - 0s - 862us/step - accuracy: 0.8519 - loss: 0.3453
Epoch 152/200
179/179 - 0s - 854us/step - accuracy: 0.8418 - loss: 0.3483
Epoch 153/200
179/179 - 0s - 881us/step - accuracy: 0.8451 - loss: 0.3475
Epoch 154/200
179/179 - 0s - 848us/step - accuracy: 0.8474 - loss: 0.3459
Epoch 155/200
179/179 - 0s - 881us/step - accuracy: 0.8496 - loss: 0.3436
Epoch 156/200
179/179 - 0s - 854us/step - accuracy: 0.8507 - loss: 0.3420
Epoch 157/200
179/179 - 0s - 872us/step - accuracy: 0.8406 - loss: 0.3469
Epoch 158/200
179/179 - 0s - 849us/step - accuracy: 0.8462 - loss: 0.3414
Epoch 159/200
179/179 - 0s - 864us/step - accuracy: 0.8395 - loss: 0.3443
Epoch 160/200
179/179 - 0s - 863us/step - accuracy: 0.8519 - loss: 0.3425
Epoch 161/200
179/179 - 0s - 861us/step - accuracy: 0.8451 - loss: 0.3452
Epoch 162/200
179/179 - 0s - 850us/step - accuracy: 0.8541 - loss: 0.3429
Epoch 163/200
179/179 - 0s - 861us/step - accuracy: 0.8384 - loss: 0.3414
Epoch 164/200
179/179 - 0s - 850us/step - accuracy: 0.8429 - loss: 0.3392
Epoch 165/200
179/179 - 0s - 867us/step - accuracy: 0.8395 - loss: 0.3440
Epoch 166/200
179/179 - 0s - 898us/step - accuracy: 0.8474 - loss: 0.3401
Epoch 167/200
179/179 - 0s - 883us/step - accuracy: 0.8496 - loss: 0.3407
Epoch 168/200
179/179 - 0s - 863us/step - accuracy: 0.8451 - loss: 0.3430
Epoch 169/200
179/179 - 0s - 878us/step - accuracy: 0.8440 - loss: 0.3425
Epoch 170/200
179/179 - 0s - 861us/step - accuracy: 0.8530 - loss: 0.3420
Epoch 171/200
179/179 - 0s - 867us/step - accuracy: 0.8395 - loss: 0.3422
Epoch 172/200
179/179 - 0s - 955us/step - accuracy: 0.8440 - loss: 0.3408
Epoch 173/200
179/179 - 0s - 887us/step - accuracy: 0.8474 - loss: 0.3425
Epoch 174/200
179/179 - 0s - 866us/step - accuracy: 0.8474 - loss: 0.3419
Epoch 175/200
179/179 - 0s - 882us/step - accuracy: 0.8429 - loss: 0.3460
Epoch 176/200
179/179 - 0s - 870us/step - accuracy: 0.8440 - loss: 0.3415
Epoch 177/200
179/179 - 0s - 859us/step - accuracy: 0.8451 - loss: 0.3393
Epoch 178/200
179/179 - 0s - 859us/step - accuracy: 0.8507 - loss: 0.3405
Epoch 179/200
179/179 - 0s - 860us/step - accuracy: 0.8496 - loss: 0.3432
Epoch 180/200
179/179 - 0s - 851us/step - accuracy: 0.8496 - loss: 0.3397
Epoch 181/200
179/179 - 0s - 868us/step - accuracy: 0.8530 - loss: 0.3395
Epoch 182/200
179/179 - 0s - 861us/step - accuracy: 0.8541 - loss: 0.3409
Epoch 183/200
179/179 - 0s - 905us/step - accuracy: 0.8395 - loss: 0.3400
Epoch 184/200
179/179 - 0s - 847us/step - accuracy: 0.8485 - loss: 0.3439
Epoch 185/200
179/179 - 0s - 857us/step - accuracy: 0.8485 - loss: 0.3408
Epoch 186/200
179/179 - 0s - 842us/step - accuracy: 0.8485 - loss: 0.3418
Epoch 187/200
179/179 - 0s - 892us/step - accuracy: 0.8462 - loss: 0.3424
Epoch 188/200
179/179 - 0s - 928us/step - accuracy: 0.8474 - loss: 0.3399
Epoch 189/200
179/179 - 0s - 854us/step - accuracy: 0.8485 - loss: 0.3410
Epoch 190/200
179/179 - 0s - 861us/step - accuracy: 0.8462 - loss: 0.3429
Epoch 191/200
179/179 - 0s - 863us/step - accuracy: 0.8406 - loss: 0.3409
Epoch 192/200
179/179 - 0s - 848us/step - accuracy: 0.8418 - loss: 0.3393
Epoch 193/200
179/179 - 0s - 875us/step - accuracy: 0.8519 - loss: 0.3381
Epoch 194/200
179/179 - 0s - 879us/step - accuracy: 0.8485 - loss: 0.3429
Epoch 195/200
179/179 - 0s - 882us/step - accuracy: 0.8451 - loss: 0.3407
Epoch 196/200
179/179 - 0s - 848us/step - accuracy: 0.8474 - loss: 0.3401
Epoch 197/200
179/179 - 0s - 859us/step - accuracy: 0.8451 - loss: 0.3388
Epoch 198/200
179/179 - 0s - 873us/step - accuracy: 0.8519 - loss: 0.3381
Epoch 199/200
179/179 - 0s - 875us/step - accuracy: 0.8530 - loss: 0.3411
Epoch 200/200
179/179 - 0s - 850us/step - accuracy: 0.8474 - loss: 0.3393
84/84 - 0s - 1ms/step